article/urls.py
from django.conf.urls import url
from . import views,list_views

urlpatterns=[
    url(r'^article-column/$',views.article_column,name='article_column'),
    url(r'^rename-column/$',views.rename_article_column,name='rename_article_column'),
    url(r'^delete-column/$',views.del_article_column,name='del_article_column'),
    url(r'^article-post/$',views.article_post,name='article_post'),
    url(r'^article-list/$',views.article_list,name='article_list'),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.article_detail,name='article_detail'),
    url(r'^del-article/$',views.del_article,name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$',views.redit_article,name='redit_article'),
    url(r'^list-article-titles/$',list_views.article_titles,name='article_titles'),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',list_views.article_detail,name='list_article_detail'),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$',list_views.article_titles,name='author_articles'),
    url(r'^like-article/$',list_views.like_article,name='like_article'),
]

blog/urls.py
from django.conf.urls import url
from . import  views

urlpatterns=[
    url(r'^$',views.blog_title,name='blog_title'),
    url(r'(?P<article_id>\d)/$',views.blog_article,name='blog_detail'),

]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'^account/',include('account.urls',namespace='account',app_name='account')),
    url(r'^article/',include('article.urls',namespace='article',app_name='article')),
    url(r'^home/',TemplateView.as_view(template_name='home.html'),name='home'),

]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from slugify import slugify

# Create your models here.
class ArticleColumn(models.Model):
    user=models.ForeignKey(User,related_name='article_column')
    column=models.CharField(max_length=200)
    created=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

class ArticlePost(models.Model):
    author=models.ForeignKey(User,related_name='article')
    title=models.CharField(max_length=200)
    slug=models.SlugField(max_length=500)
    column=models.ForeignKey(ArticleColumn,related_name='article_column')
    body=models.TextField()
    created=models.DateTimeField(default=timezone.now)
    updated=models.DateTimeField(auto_now=True)
    users_like=models.ManyToManyField(User,related_name='articles_like',blank=True)

    class Meta:
        ordering=('title',)
        index_together=(('id','slug'),)
    def __str__(self):
        return self.title

    def save(self,*args,**kargs):
        self.slug=slugify(self.title)
        super(ArticlePost, self).save(*args,**kargs)

    def get_absolute_url(self):
        return reverse('article:article_detail',args=[self.id,self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail',args=[self.id,self.slug])

article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model=ArticleColumn
        fields=('column',)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model=ArticlePost
        fields=('title','body')

article/views.py
import json
from django.core.paginator import EmptyPage,Paginator,PageNotAnInteger
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn,ArticlePost
from .forms import ArticleColumnForm,ArticlePostForm
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views.decorators.http import require_POST
# Create your views here.
@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method=='GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request,'article/column/article-column.html',{'columns':columns,'column_form':column_form})
    if request.method=='POST':
        column_name=request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id,column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name)
            return HttpResponse('1')

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name=request.POST['column_name']
    column_id=request.POST['column_id']
    try:
        line=ArticleColumn.objects.get(id=column_id)
        line.column=column_name
        line.save()
        return HttpResponse('1')
    except:
        return HttpResponse('0')

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id=request.POST['column_id']
    try:
        line=ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('0')

@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method=='POST':
        article_post_form=ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd=article_post_form.cleaned_data
            try:
                new_article=article_post_form.save(commit=False)
                new_article.author=request.user
                new_article.column=request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                id=new_article.id
                slug=new_article.slug
                return HttpResponse(json.dumps({'e': 1,'id':id,'slug':slug}))
            except:
                return HttpResponse(json.dumps({'e': 2}))
        else:
            return HttpResponse(json.dumps({'e': 3}))
    else:
        article_post_form=ArticlePostForm()
        article_columns=request.user.article_column.all()
        return render(request,'article/column/article_post.html',{'article_post_form':article_post_form,'article_columns':article_columns})

@login_required(login_url='/account/login')
def article_list(request):
    articles_list=ArticlePost.objects.filter(author=request.user)
    paginator=Paginator(articles_list,5)
    page=request.GET.get('page')
    try:
        current_page=paginator.page(page)
        articles=current_page.object_list
    except PageNotAnInteger:
        current_page=paginator.page(1)
        articles=current_page.object_list
    except EmptyPage:
        current_page=paginator.page(paginator.num_pages)
        articles=current_page.object_list
    return render(request,'article/column/article_list.html',{"articles":articles,'page':current_page})

@login_required(login_url='/account/login')
def article_detail(request,id,slug):
    article=get_object_or_404(ArticlePost,id=id,slug=slug)
    return render(request,'article/column/article_detail.html',{'article':article})

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id=request.POST['article_id']
    try:
        article=ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request,article_id):
    if request.method=="GET":
        article_columns=request.user.article_column.all()
        article=ArticlePost.objects.get(id=article_id)
        this_article_form=ArticlePostForm(initial={"title":article.title})
        this_article_column=article.column
        return render(request,'article/column/redit_article.html',{'article':article,'article_columns':article_columns,'this_article_column':this_article_column,'this_article_form':this_article_form})
    else:
        redit_article=ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column=request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title=request.POST['title']
            redit_article.body=request.POST['body']
            redit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('2')

templates/article/list/article_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}article detail{% endblock %}
{% block content %}
{% with total_likes=article.users_like.count users_like=article.users_like.all %}
    <div class="container" style="margin-top:50px;">
        <div class="col-md-9">
                    <header>
            <h1>{{ article.title }}</h1>
            <p>
                <a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
                <span style="margin-left: 20px;" class="glyphicon glyphicon-thumbs-up"> {{ total_likes }}like{{ total_likes|pluralize }}</span>
                <span style="margin-left: 20px;">{{ total_views }}view{{ total_views|pluralize }}</span>
            </p>
        </header>
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">

        <div id="editormd-view">
            <textarea id="append-test" style="display:none;">{{ article.body }}</textarea>
        </div>
    <div>
        <p class="text-center">
            <a onclick="like_article({{ article.id }},'like')" href="#"><span class="glyphicon glyphicon-thumbs-up">like</span></a>|
            <a onclick="like_article({{ article.id }},'unlike')" href="#"><span class="glyphicon glyphicon-thumbs-down">unlike</span></a>
        </p>
    </div>
    <div>
        <p class="text-center"><strong>点赞的读者</strong></p>
        {% for user in article.users_like.all %}
            <p class="text-center">{{ user.username }}</p>
        {% empty %}
            <p class="text-center">还没人表态</p>
        {% endfor %}
    </div>
        </div>
    <div class="col-md-3">
        <p class="text-center"><h3>最受欢迎文章</h3></p>
        <ol>
            {% for article_rank in most_viewed %}
                <li><a href="{{ article_rank.get_url_path }}">{{ article_rank.title }}</a></li>
            {% endfor %}
        </ol>
    </div>

    </div>
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
    $(function(){
        editormd.markdownToHTML("editormd-view",{
            htmlDecode:"style,script,iframe",
            emoji:true,
            taskList:true,
            tex:true,
            flowChart:true,
            sequenceDiagram:true,
        });
    });
    function like_article(id,action) {
        $.ajax({
            url:"{% url 'article:like_article' %}",
            type:"POST",
            data:{"id":id,"action":action},
            success:function (e) {
              if(e=="1"){
                  layer.msg("Thanks");
                  window.location.reload();
              }else{
                  layer.msg("Keep doing");
                  window.location.reload();
              }
            },
        });
    }
    </script>
{% endwith %}
{% endblock %}

templates/article/list/article_titles.html
{% extends 'base.html' %}
{% block titile %}articles{% endblock %}
{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>阅读，丰富头脑，善化行为</h1>
    </div>
    <div class="container">
        {% for article in articles %}
            <div class="list-group">
                <a href="{{ article.get_url_path }}" class="list-group-item active">
                    <h4 class="list-group-item-heading">{{ article.title }}</h4>
                    <a href="{% url 'article:author_articles' article.author.username %}"><p class="list-group-item-text">作者：{{ article.author.username }}</p></a>
                    <p class="list-group-item-text">概要:{{ article.body|slice:'10'|linebreaks }}</p>
                </a>
            </div>
        {% endfor %}
    {% include 'paginator.html' %}
    </div>
{% endblock %}

templates/article/list/author_articles.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}articles{% endblock %}
{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>阅读，丰富头脑，善化行为</h1>
    </div>
    <div class="container">
        <div class="col-md-8">
            {% for article in articles %}
                <div class="list-group">
                    <a href="{{ article.get_url_path }}" class="list-group-item active">
                        <h4 class="list-group-item-heading">{{ article.title }}</h4>
                    </a>
                <p class="list-group-item-text">作者：<a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a></p>
                <p class="list-group-item-text">概要:{{ article.body|slice:'20'|linebreaks }}</p>
                </div>
            {% endfor %}
    {% include 'paginator.html' %}
        </div>
        <div class="col-md-4">
            <div>
                {% if userinfo.photo %}
                    <img src="{{ userinfo.photo|striptags }}" class="img-circle" id="my_photo" name="user_face">
                {% else %}
                    <img name="user_face" src="{% static 'images/IMG_2328.JPG' %}" class="img-circle" id="my_photo">
                {% endif %}
            </div>
            <div>
                <p>{{ user1.username }}</p>
                {% if userinfo %}
                    <p>{{ userinfo.company }}</p>
                    <p>{{ userinfo.aboutme }}</p>
                {% else %}
                    <p>这个作者太懒了，什么都没有留下</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}